trainingInput:
        scaleTier: CUSTOM
        masterType: n1-standard-4
        masterConfig:
                acceleratorConfig:
                         count: 1
                         type: NVIDIA_TESLA_T4
