_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    NUM_CLASSES: 1
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 15000
  IMS_PER_BATCH: 2
  CHECKPOINT_PERIOD: 10000
  BASE_LR: 0.01
DATASETS:
  TRAIN: ("car_damage_train",)
  TEST: ("car_damage_val",)
DATALOADER:
  NUM_WORKERS: 2
  FILTER_EMPTY_ANNOTATIONS: False # using this to allow images without annotation (at this point, they are filtered out when creating the jsons)
INPUT:
  MASK_FORMAT: "bitmask"
TEST:
  EVAL_PERIOD: 500
