_BASE_: "Base-BlendMask.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
    DEFORM_ON_PER_STAGE: [False, True, True, True]
    DEFORM_MODULATED: True
    DEFORM_INTERVAL: 3
SOLVER:
  STEPS: (280000, 360000)
  MAX_ITER: 15000
  CHECKPOINT_PERIOD: 5000
  #BASE_LR: 0.005
INPUT:
  MIN_SIZE_TRAIN: (640, 864)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MAX_SIZE_TRAIN: 1440
  MASK_FORMAT: "bitmask"
  CROP:
    ENABLED: True
TEST:
  EVAL_PERIOD: 500
DATASETS:
  TRAIN: ("car_damage_train",)
  TEST: ("car_damage_val",)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False # using this to allow images without annotation (at this point, they are filtered out when creating the jsons)