_BASE_: "Base-BlendMask.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 5000
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 1000
DATASETS:
  TRAIN: ("car_damage_train",)
  TEST: ("car_damage_val",)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False # using this to allow images without annotation (at this point, they are filtered out when creating the jsons)
INPUT:
  MASK_FORMAT: "bitmask"